services:

  server:
    build: .
    container_name: server
    environment:
      NODE_ENV: development
      PORT: 80
      APP_NAME: server
      NX_DAEMON: true
    ports:
      - '80:80'
    volumes:
      - ./apps:/usr/src/app/apps

  website:
    build: .
    container_name: website
    environment:
      NODE_ENV: development
      PORT: 4200
      APP_NAME: website
      NX_DAEMON: true
    ports:
      - '4200:4200'
    volumes:
      - ./apps:/usr/src/app/apps

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'fmdb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_TCP_PORT: 3170
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3170:3170'
      # Where our data will be persisted
    volumes:
      - ./fmdb:/var/lib/mysql
# Names our volume
volumes:
  fmdb: