services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'fmdb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_TCP_PORT: 3170
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3170:3170'
      # Where our data will be persisted
    volumes:
      - ./fmdb:/var/lib/mysql
# Names our volume
volumes:
  fmdb: