services:
  prod-website:
    build:
      context: .
      dockerfile: prod.Dockerfile
    ports:
      - "4200:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./dist/apps/website:/usr/share/nginx/html
    restart: always

